In [1]:
#TRANSFER LEARNING FOR SENTIMENT ANALYSIS
# TRANSFER LEARNING (using a pre trained) MODEL IS ALREADY EXISTING --> using it

In [2]:
#trained our model --> X and Y
# what is Y is not there only X is there

#new movie is release and viewers are giving the comments
# some 1 lakh comments are there --> find the over all feedback(+ve or -ve)
#use a pre trained model --> over all score

In [3]:
#pre-trained model for sentiment analysis

In [4]:
#vader is the library for sentiment analysis

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
trip=pd.read_csv(r"C:\Users\shrus\Downloads\Trip_advisor_review.csv")

In [3]:
import nltk  
from nltk.corpus import stopwords

In [4]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer #function

In [5]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\shrus\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [6]:
sent = SentimentIntensityAnalyzer()

In [7]:
sent.polarity_scores('i enjoyed watching the movie. Movie was was very good. it was awesome')

{'neg': 0.0, 'neu': 0.459, 'pos': 0.541, 'compound': 0.8908}

In [8]:
sent.polarity_scores("today is neutral")

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [9]:
trip.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [10]:
trip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20491 entries, 0 to 20490
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  20491 non-null  object
 1   Rating  20491 non-null  int64
dtypes: int64(1), object(1)
memory usage: 320.3+ KB

In [11]:
trip.shape

(20491, 2)

In [ ]:
#problem statement/ requirement--> comapny has launched a new product
#and user are giving the comments/ feedback --->
#company want to find if overall feedback is +ve or -ve

#CONSIDER rating column is not present

In [12]:
score_list=[]
for i in range(0, trip.shape[0]):
    score=sent.polarity_scores(trip['Review'][i])
    score_list.append(score['compound'])

In [20]:
score_list

[0.9747,
 0.9787,
 0.9889,
 0.9912,
 0.9797,
 0.987,
 0.9925,
 0.959,
 0.9618,
 0.9756,
 0.9666,
 0.9242,
 0.9859,
 0.7584,
 0.9608,
 0.8496,
 0.9905,
 0.9948,
 0.93,
 0.9891,
 0.9754,
 0.9831,
 0.9661,
 0.969,
 0.9153,
 0.9509,
 0.9753,
 -0.3814,
 0.9954,
 0.9336,
 0.9839,
 0.9468,
 0.8716,
 0.8874,
 0.9022,
 0.9884,
 0.9913,
 0.9586,
 0.954,
 0.9565,
 -0.9249,
 0.9274,
 -0.9169,
 0.9796,
 -0.1561,
 0.9829,
 0.8413,
 0.7592,
 0.9776,
 0.9526,
 0.9782,
 0.9895,
 0.977,
 0.9578,
 0.5563,
 0.8842,
 0.9549,
 0.9936,
 0.9703,
 0.9962,
 0.9847,
 0.9872,
 0.9915,
 0.9913,
 0.9872,
 -0.936,
 0.9932,
 0.9904,
 0.7351,
 0.3182,
 0.9441,
 -0.9228,
 0.9957,
 0.9669,
 0.9872,
 0.9929,
 -0.4261,
 -0.2023,
 0.9158,
 -0.743,
 0.9507,
 0.9656,
 0.9882,
 0.6846,
 0.9648,
 0.9403,
 0.9712,
 0.9568,
 -0.8889,
 0.9559,
 0.9304,
 0.9285,
 0.9148,
 0.9531,
 0.9833,
 0.9761,
 0.9097,
 0.235,
 0.9771,
 -0.9065,
 0.9727,
 0.6483,
 0.9982,
 0.8412,
 0.9859,
 0.9687,
 0.9643,
 0.9792,
 0.9978,
 0.8689,
 0.9968,
 0.9887,
 0.9867,
 0.9121,
 0.9558,
 0.9919,
 0.9874,
 0.9493,
 -0.4226,
 0.9632,
 0.8807,
 0.9918,
 0.9601,
 0.9931,
 0.9485,
 0.9756,
 0.926,
 0.9892,
 0.9837,
 0.9788,
 0.9909,
 0.8631,
 0.959,
 0.9842,
 0.6242,
 -0.8107,
 0.9934,
 0.9892,
 0.9538,
 0.982,
 -0.9099,
 -0.7334,
 0.3975,
 0.9529,
 0.9843,
 0.9627,
 0.9136,
 0.9673,
 0.9619,
 0.9831,
 0.9809,
 0.854,
 0.9856,
 0.8519,
 0.8388,
 -0.5763,
 0.765,
 0.9956,
 0.3197,
 0.986,
 -0.8205,
 0.9836,
 0.891,
 0.9844,
 0.9607,
 0.9678,
 0.9921,
 0.9686,
 0.8953,
 0.9886,
 0.9914,
 0.967,
 0.9674,
 0.9319,
 -0.8316,
 0.802,
 -0.9241,
 0.9892,
 0.9872,
 0.6532,
 0.9661,
 -0.9902,
 0.8891,
 0.9682,
 0.9826,
 0.9835,
 0.9509,
 -0.3187,
 0.9722,
 0.9168,
 0.7854,
 -0.2792,
 0.7652,
 0.9305,
 0.3982,
 0.9693,
 -0.9733,
 -0.5267,
 0.9939,
 0.9856,
 0.8105,
 0.6249,
 -0.7195,
 0.9118,
 0.8511,
 0.9868,
 0.9407,
 0.9607,
 0.9542,
 0.6555,
 0.5267,
 -0.8465,
 0.9705,
 0.9732,
 0.9694,
 0.9719,
 0.7845,
 0.9774,
 0.875,
 0.9601,
 0.9745,
 0.9793,
 0.9938,
 0.8982,
 0.9703,
 0.2134,
 0.945,
 0.9601,
 0.9874,
 0.9882,
 0.9735,
 -0.2206,
 0.9938,
 -0.5609,
 0.9639,
 0.9081,
 0.9755,
 0.9509,
 0.8578,
 0.9554,
 0.9766,
 0.9848,
 0.9891,
 0.7269,
 0.9747,
 0.9694,
 0.9923,
 0.982,
 -0.6946,
 0.8625,
 0.9556,
 0.9779,
 0.7618,
 0.9559,
 0.9011,
 0.7845,
 0.8442,
 -0.0966,
 0.9524,
 -0.4767,
 0.9938,
 0.9918,
 0.1333,
 0.9833,
 0.9712,
 -0.4395,
 0.9924,
 0.967,
 0.8979,
 0.6239,
 0.995,
 0.9801,
 0.9911,
 0.9922,
 0.9768,
 0.9217,
 0.9635,
 0.9815,
 0.9689,
 0.9743,
 0.9559,
 0.9829,
 0.9873,
 0.6369,
 0.9872,
 0.3182,
 0.9936,
 0.99,
 0.9897,
 0.8505,
 0.7546,
 0.3544,
 -0.6757,
 0.9898,
 0.5707,
 0.9806,
 -0.5108,
 0.7456,
 0.9935,
 0.9633,
 0.8669,
 0.9865,
 0.968,
 0.7627,
 0.9701,
 0.9501,
 0.9524,
 0.9872,
 0.6705,
 0.8625,
 -0.7432,
 -0.8093,
 0.942,
 0.9875,
 0.9938,
 0.97,
 0.9899,
 0.8346,
 0.9309,
 0.9628,
 -0.7504,
 0.5657,
 0.5529,
 0.7639,
 0.9875,
 0.9866,
 0.9687,
 0.8688,
 0.9912,
 0.9868,
 -0.7426,
 0.9975,
 -0.7269,
 0.8658,
 -0.8386,
 0.8925,
 0.2607,
 0.9843,
 0.8074,
 0.9701,
 0.6249,
 0.8935,
 -0.6136,
 0.9551,
 0.9956,
 0.9652,
 0.9332,
 0.6369,
 -0.8049,
 -0.5699,
 0.9821,
 0.9853,
 0.986,
 0.3877,
 0.9903,
 0.9802,
 0.9177,
 0.9842,
 0.992,
 0.7351,
 0.9785,
 0.9796,
 0.9812,
 0.991,
 0.9403,
 -0.9625,
 0.926,
 -0.836,
 0.9816,
 0.7788,
 0.5994,
 0.9893,
 0.9953,
 0.9846,
 0.9987,
 0.9927,
 0.9559,
 -0.2561,
 0.5577,
 -0.91,
 0.9212,
 0.9842,
 0.9448,
 0.9815,
 0.9417,
 0.9371,
 0.8934,
 0.7087,
 0.9778,
 -0.8747,
 0.9867,
 0.946,
 0.974,
 -0.9612,
 0.9893,
 0.9947,
 0.9761,
 0.9001,
 0.9878,
 0.872,
 0.9535,
 0.9783,
 0.9786,
 0.8717,
 0.9946,
 0.9167,
 0.9724,
 0.1275,
 0.9545,
 0.9241,
 0.9769,
 0.9931,
 0.0485,
 0.9639,
 0.9562,
 0.9869,
 0.9337,
 0.9884,
 0.9869,
 0.9802,
 0.9003,
 0.9848,
 0.9464,
 -0.128,
 -0.5414,
 0.9786,
 0.7269,
 0.9615,
 0.9517,
 0.952,
 0.9023,
 0.9228,
 -0.8532,
 -0.647,
 0.9642,
 0.9916,
 0.9895,
 0.9459,
 0.9033,
 0.9844,
 0.9819,
 0.997,
 0.9961,
 0.9968,
 0.9924,
 -0.6742,
 0.9735,
 0.993,
 0.9614,
 0.9694,
 0.9666,
 0.9878,
 0.9601,
 0.34,
 0.9556,
 0.8523,
 0.8142,
 0.296,
 0.8891,
 0.9802,
 0.8993,
 0.7394,
 0.9888,
 -0.9195,
 0.9403,
 0.9965,
 0.9742,
 0.9623,
 -0.4767,
 0.9686,
 0.5574,
 0.9073,
 0.9791,
 0.7964,
 0.9892,
 0.969,
 0.9922,
 0.8481,
 0.8591,
 0.6336,
 -0.5719,
 0.8267,
 -0.9683,
 -0.8639,
 0.9573,
 -0.9141,
 -0.5635,
 0.9974,
 0.6249,
 0.7956,
 0.9898,
 0.9823,
 0.8315,
 0.9761,
 0.9559,
 0.8807,
 -0.3691,
 0.9872,
 0.9623,
 0.9287,
 0.9153,
 0.9451,
 0.849,
 0.802,
 0.9545,
 0.9468,
 0.993,
 0.992,
 0.9696,
 -0.9794,
 0.8399,
 0.9954,
 0.6581,
 0.9787,
 0.9712,
 0.9606,
 0.999,
 0.9963,
 0.9967,
 0.9986,
 0.998,
 0.9746,
 0.9758,
 0.2226,
 0.9584,
 0.9905,
 0.9879,
 0.8074,
 0.99,
 0.8689,
 0.9817,
 0.9847,
 0.9899,
 0.9913,
 0.5983,
 0.9519,
 0.9638,
 -0.1867,
 0.9899,
 0.9201,
 0.9542,
 0.9599,
 0.4404,
 -0.9001,
 0.9729,
 0.9806,
 -0.4201,
 0.9866,
 0.4781,
 0.9948,
 0.8899,
 0.9839,
 0.9201,
 0.8591,
 0.4035,
 0.9688,
 0.4215,
 0.1531,
 0.7166,
 0.6352,
 0.9552,
 0.9312,
 0.9855,
 0.9802,
 0.9958,
 0.9803,
 0.8324,
 0.9274,
 0.9982,
 0.9477,
 0.9702,
 0.9788,
 0.9942,
 0.8702,
 0.8967,
 0.9817,
 0.9694,
 0.962,
 0.9826,
 0.9932,
 0.992,
 0.9419,
 0.9812,
 0.9442,
 0.9957,
 0.9851,
 0.9657,
 -0.9843,
 0.9838,
 0.3979,
 0.9947,
 0.9289,
 0.9638,
 0.9371,
 0.9913,
 -0.9578,
 -0.744,
 0.8999,
 0.9796,
 0.9081,
 0.0534,
 0.3987,
 0.978,
 0.9902,
 0.948,
 -0.8733,
 0.9896,
 0.9866,
 0.9817,
 0.9877,
 0.9714,
 0.9313,
 0.9478,
 0.9911,
 0.91,
 0.8717,
 0.9771,
 0.9217,
 0.9287,
 -0.0429,
 0.9735,
 0.9853,
 0.9785,
 0.9769,
 0.9872,
 0.8998,
 0.9831,
 0.017,
 0.9347,
 -0.924,
 0.992,
 0.9773,
 0.9948,
 -0.0152,
 0.9872,
 0.9837,
 0.9818,
 0.9937,
 -0.21,
 0.9878,
 0.9731,
 0.9471,
 0.9658,
 0.9682,
 0.9382,
 0.9946,
 0.9185,
 0.9884,
 0.9901,
 0.9646,
 0.9805,
 0.9938,
 0.9819,
 0.9843,
 0.5868,
 0.9917,
 0.9968,
 0.9838,
 0.9808,
 0.9914,
 -0.464,
 0.9796,
 0.8892,
 0.9188,
 0.9892,
 0.3597,
 0.9885,
 0.6677,
 0.7594,
 0.9562,
 -0.9858,
 0.1548,
 0.9474,
 0.9887,
 0.8956,
 0.1896,
 0.9744,
 0.9206,
 0.9871,
 0.9463,
 0.9752,
 0.8176,
 0.9815,
 0.9794,
 0.9382,
 0.9906,
 -0.5996,
 0.7408,
 -0.846,
 0.9857,
 0.981,
 0.9899,
 -0.9497,
 0.9919,
 0.9875,
 0.0003,
 0.9509,
 -0.2755,
 -0.8347,
 0.3744,
 -0.9485,
 0.9461,
 0.9493,
 0.9696,
 0.5235,
 0.9775,
 0.9819,
 0.9596,
 0.9934,
 -0.9685,
 0.9081,
 0.9816,
 0.9808,
 0.9714,
 0.9632,
 0.9698,
 0.0253,
 0.5806,
 0.9828,
 0.9341,
 0.9686,
 0.9063,
 -0.1027,
 -0.5945,
 -0.5362,
 0.973,
 0.9744,
 0.7717,
 0.7269,
 0.9821,
 0.9325,
 0.9877,
 -0.7658,
 0.9867,
 0.7683,
 0.9537,
 0.9698,
 0.9808,
 0.9834,
 0.0552,
 0.9733,
 0.9968,
 0.9844,
 0.9701,
 0.7188,
 0.9847,
 0.6286,
 0.9838,
 0.9869,
 0.9015,
 0.926,
 0.9522,
 0.7748,
 0.9827,
 0.986,
 -0.7514,
 0.9649,
 0.9571,
 0.988,
 0.9567,
 0.9944,
 0.8225,
 0.9814,
 0.9887,
 0.8834,
 0.9638,
 0.1027,
 0.8908,
 0.9861,
 0.8402,
 0.976,
 -0.1695,
 0.9527,
 0.9899,
 0.9607,
 0.9578,
 0.9432,
 0.9838,
 0.9887,
 0.9892,
 0.9933,
 0.9814,
 0.987,
 0.9501,
 0.9895,
 0.9915,
 0.9326,
 0.7096,
 0.9484,
 0.9633,
 0.9745,
 0.9857,
 -0.0977,
 0.9709,
 0.9538,
 0.9848,
 0.9674,
 0.5562,
 0.9806,
 0.9843,
 0.9577,
 0.9576,
 0.9933,
 0.9792,
 0.975,
 0.983,
 0.9706,
 0.9744,
 0.9918,
 0.8715,
 0.9761,
 0.99,
 0.9819,
 0.3818,
 0.9836,
 0.3205,
 0.9432,
 0.8942,
 0.9702,
 0.8126,
 0.927,
 0.8397,
 0.9948,
 0.9559,
 0.8807,
 0.9274,
 0.9446,
 0.9014,
 0.7064,
 0.9585,
 -0.4337,
 0.9907,
 0.3408,
 0.9884,
 0.9928,
 0.9678,
 0.1566,
 0.7906,
 0.802,
 0.9475,
 -0.8807,
 0.9794,
 0.9628,
 0.926,
 0.9936,
 0.9847,
 0.9804,
 -0.8643,
 0.2375,
 0.2853,
 -0.1531,
 0.9942,
 0.9801,
 0.9816,
 0.9413,
 0.9759,
 0.9571,
 0.9852,
 -0.7956,
 0.9847,
 0.9839,
 0.931,
 0.9509,
 0.9948,
 0.9821,
 0.9951,
 0.9611,
 0.9233,
 0.9938,
 0.9535,
 0.9642,
 0.9744,
 0.9661,
 0.8807,
 0.9627,
 0.9923,
 0.8656,
 0.9951,
 0.9887,
 0.9337,
 0.9048,
 0.9799,
 0.9975,
 0.9744,
 0.9447,
 0.8934,
 0.4404,
 0.9451,
 0.9062,
 0.9705,
 0.9578,
 0.9958,
 0.9559,
 -0.705,
 0.9182,
 0.9705,
 0.9766,
 0.9509,
 0.9558,
 0.9923,
 0.9091,
 0.9261,
 0.9939,
 0.9967,
 0.9628,
 0.9892,
 0.7841,
 0.9896,
 0.9701,
 0.9738,
 0.9477,
 0.985,
 0.9015,
 0.9674,
 0.9509,
 0.9845,
 0.9538,
 0.9867,
 0.9884,
 0.9929,
 0.9764,
 0.9337,
 0.9825,
 0.9898,
 0.9876,
 0.9384,
 0.8807,
 -0.5058,
 0.9682,
 0.9862,
 0.9851,
 0.9957,
 0.9858,
 0.9583,
 0.9786,
 -0.7011,
 0.9118,
 0.9652,
 0.962,
 0.9693,
 0.9862,
 0.9695,
 0.9135,
 0.6486,
 0.8983,
 0.9885,
 0.9432,
 0.9913,
 0.9557,
 0.91,
 0.9327,
 0.9887,
 0.974,
 0.9524,
 0.9767,
 0.1531,
 0.9632,
 0.9862,
 0.8815,
 0.9818,
 0.9801,
 0.9922,
 0.9712,
 0.9783,
 0.9858,
 0.9925,
 0.9839,
 0.9888,
 0.9819,
 0.8885,
 0.9677,
 0.6705,
 0.989,
 0.9756,
 0.6808,
 0.977,
 0.5719,
 0.5705,
 0.9716,
 0.9871,
 0.9879,
 -0.6287,
 0.992,
 0.9719,
 0.7234,
 -0.8904,
 0.9019,
 0.9803,
 -0.5175,
 0.8625,
 0.947,
 -0.4166,
 -0.9018,
 0.9867,
 0.999,
 0.6808,
 0.9442,
 0.6964,
 0.9628,
 0.8354,
 ...]

In [13]:
import numpy as np

In [14]:
avg_score=np.mean(score_list)
print(f"Average:{avg_score}")

Average:0.8034298862915427

In [15]:
avg_score=max(score_list)
print(f"Max:{avg_score}")

Max:0.9999

In [16]:
avg_score=min(score_list)
print(f"Min:{avg_score}")

Min:-0.9974

In [17]:
trip.describe()

             Rating
count  20491.000000
mean       3.952223
std        1.233030
min        1.000000
25%        3.000000
50%        4.000000
75%        5.000000
max        5.000000

In [18]:
pd.Series(score_list).describe()

count    20491.000000
mean         0.803430
std          0.455671
min         -0.997400
25%          0.918400
50%          0.973800
75%          0.988800
max          0.999900
dtype: float64

In [24]:
imdb=pd.read_csv(r"C:\Users\shrus\Downloads\IMDB Dataset.csv.xls")

In [25]:
imdb.head()

                                   review\tsentiment
0  One of the other reviewers has mentioned that ...
1  A wonderful little production. <br /><br />The...
2  I thought this was a wonderful way to spend ti...
3  Basically there's a family where a little boy ...
4  Petter Mattei's "Love in the Time of Money" is...

In [26]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review	sentiment  50000 non-null  object
dtypes: object(1)
memory usage: 390.8+ KB

In [27]:
imdb.shape

(50000, 1)

In [29]:
score_list=[]
for i in range(0 , imdb.shape[0]):
    score =sent.polarity_scores(imdb['review'][i])
    score_list.append(score['compound'])

KeyError: 'review'

In [30]:
pd.Series(score_list).describe()

count       0
unique      0
top       NaN
freq      NaN
dtype: object

In [31]:
pip install TextBlob

Requirement already satisfied: TextBlob in c:\users\shrus\anaconda3\lib\site-packages (0.20.1)
Requirement already satisfied: nltk>=3.9 in c:\users\shrus\anaconda3\lib\site-packages (from TextBlob) (3.9.2)
Requirement already satisfied: click in c:\users\shrus\anaconda3\lib\site-packages (from nltk>=3.9->TextBlob) (8.2.1)
Requirement already satisfied: joblib in c:\users\shrus\anaconda3\lib\site-packages (from nltk>=3.9->TextBlob) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\shrus\anaconda3\lib\site-packages (from nltk>=3.9->TextBlob) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\shrus\anaconda3\lib\site-packages (from nltk>=3.9->TextBlob) (4.67.1)
Requirement already satisfied: colorama in c:\users\shrus\anaconda3\lib\site-packages (from click->nltk>=3.9->TextBlob) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [32]:
from textblob import TextBlob #install
blob=TextBlob("i enjoyed watching the movie. movie was good")
blob.sentiment

Sentiment(polarity=0.6, subjectivity=0.65)

In [33]:
blob=TextBlob("movie was not good it was waste of time")
blob.sentiment[0]

-0.275

In [34]:
score_list_blob=[]
for i in range(0, trip.shape[0]):
    blob=TextBlob(trip['Review'][i])
    score_list_blob.append(blob.sentiment[0])

In [ ]:
pip install flair